### ISSUE TITLE
Identify the framework for the client prototype

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#16]
Here are some aspects to consider for the selection of the web client framework

- The pages generated "by default" should be appealing / meet modern UI standard (important for positive feedback from LT)
- Because @vpchung is implementing the client, it should be a framework she knows or a different framework with a low learning curve.
- We should accept that the production client will use a different framework. But the best scenario is still if the production client can be achieved by further working on the codebase of the prototype.

@vpchung Could you follow [this tutorial](https://www.freecodecamp.org/news/angular-8-tutorial-in-easy-steps/) and tell me what your first impressions of Angular are? I have develop one large project with it in 2019 and would enjoy providing support and even help with the implementation if times permit.

**Comment by tschaffter** [comment]
https://trends.google.com/trends/explore?cat=31&q=Vue.js,React,Angular

**Comment by vpchung** [comment]
I was going to move forward with React since that's what the platform uses... but more than happy to look at both options! I played with Angular a couple years ago, and I remember it being not that bad.

**Comment by tschaffter** [comment]
On a side note, we now have a library client for Python.

https://github.com/Sage-Bionetworks/rocc-client

**Comment by tschaffter** [comment]
Candidate Sage portal codebase to start from: [Cancer Complexity Knowledge Portal](https://staging.cancercomplexity.synapse.org/)

**Comment by tschaffter** [comment]
[Preview of a challenge exploration page](https://docs.google.com/presentation/d/1mpt8-6zqPtBtWV1PN3hgzJeijNBT-ExDFQUaVEmb0rU/edit#slide=id.gac1b32db1f_0_269) made by @vpchung.

**Comment by vpchung** [comment]
@tschaffter after some research, I have decided to move forward with using React as the framework, especially since Sage has some existing technologies that I could re-use or use as reference.

**Comment by tschaffter** [comment]
Did you have a chance to try the Angular tutorial I linked in the original message of this ticket? If not I plan to give it a shot myself. The tutorial use an Angular generator and the generated website looks cool.

Meanwhile and before we close this ticket, can you identify a boilerplate for React? Preferably we are looking for a generator widely adopted by the React community that can be used to generate a boilerplate web client.

**Comment by tschaffter** [comment]
Replaced by these R&BT tickets:

- https://github.com/Sage-Bionetworks/research-benchmarking-technology/issues/3
- https://github.com/Sage-Bionetworks/research-benchmarking-technology/issues/4
- https://github.com/Sage-Bionetworks/research-benchmarking-technology/issues/5
