### ISSUE TITLE
Move existing tickets to the new project board

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#30]
Move the existing tickets to that they are visible to the new project board.

Tips:

- Identify if an existing ticket is a task/story/epic
- Link tasks to stories/epics and stories to epics

**Comment by jiaxinmachine88** [comment]
How mission critical is this? 

Currently, the project beta exists somewhat separately from the original projects and requires manually updating each issue. I estimate it will take me about 3 hours of focused time to do this.  

- 50 issues for the ROCC backlog and sprint boards 
- 19 issues for RBT Backlog 
- 100+ issues for NLP Sandbox sprint board 

Additional documentation on Github Project Beta: 
[Converting a Regular Project to Project Beta](https://github.community/t/convert-a-regular-project-to-a-project-beta/202779)
[Issues/Project Beta at Repo Level ](https://github.com/github/feedback/discussions/6229)

**Comment by tschaffter** [comment]
@jiaxinmachine88 I would say that it would be nice to have the old tickets ported to the new board by the time we start planning the next sprint, which will focus on hardening the current implementation. Hence it will be useful to have past tickets / issues reported to identify the bugs we want to fix. This basically gives us three weeks to move the tickets to the new project.

**Comment by tschaffter** [comment]
Done
