### ISSUE TITLE
Publish coverage report to coveralls

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/rocc#33]
Using this example: https://github.com/Sage-Bionetworks/prov-service

Early I hit the error below. The issue is because the current version of `coveralls` is not compatible with the package `coverage>=5`. Using `coverage==4.5.4` solves this issue.

```
$ coverage run --source=mypkg -m pytest openapi_server/
======================================================================== test session starts =========================================================================
platform linux -- Python 3.8.5, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
Using --randomly-seed=2929460938
rootdir: /mnt/c/Users/thoma/Documents/dev/rocc/server
plugins: randomly-3.5.0, cov-2.10.1
collected 16 items

openapi_server/test/integration/test_organization_controller.py ....                                                                                           [ 25%]
openapi_server/test/integration/test_tag_controller.py ....                                                                                                    [ 50%]
openapi_server/test/integration/test_person_controller.py ....                                                                                                 [ 75%]
openapi_server/test/integration/test_grant_controller.py ....                                                                                                  [100%]

========================================================================== warnings summary ==========================================================================
../../../../../../../../home/tschaffter/.local/lib/python3.8/site-packages/flask/_compat.py:139
  /home/tschaffter/.local/lib/python3.8/site-packages/flask/_compat.py:139: DeprecationWarning: 'flask.json_available' is deprecated and will be removed in version 2.0.0.
    self._warn()

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=================================================================== 16 passed, 1 warning in 7.85s ====================================================================
Coverage.py warning: Module mypkg was never imported. (module-not-imported)
Coverage.py warning: No data was collected. (no-data-collected)
(rocc) tschaffter@DESKTOP-H29C5A0:~/dev/rocc/server$ coveralls
Traceback (most recent call last):
  File "/home/tschaffter/.conda/envs/rocc/bin/coveralls", line 8, in <module>
    sys.exit(wear())
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter' from 'coverage.report' (/home/tschaffter/.conda/envs/rocc/lib/python3.8/site-packages/coverage/report.py)
```

**Comment by thomasyu888** [comment]
`pytest` itself has a `--coverage` option you can install: https://pypi.org/project/pytest-cov/

**Comment by tschaffter** [comment]
The command generated by the openapi-generator is similar to the command you showed and already use `pytest-cov`. However I was not able to generated an output file that coveralls can read.

While I can run a `pytest` command followed by a `coveralls` command similarly to [this example](https://github.com/Sage-Bionetworks/prov-service/blob/c71ef69dc79595e926364afe1e18dc31983fadb6/.travis.yml#L37-L40), I observed that it's not possible to run the `coveralls` command just after a `tox` command, i.e. the solution seems to include `coveralls` as part of tox.

**Comment by tschaffter** [comment]
The difference lies in the content of the file `.coverage`.

When running the command `pytest --cov-config=setup.cfg --cov=openapi_server -v` in the terminal, `.coverage` looks as shown below. Running the command `coveralls` just after successfully publish the results to coveralls.io.

```
!coverage.py: This is a private format, don't read it directly!{"lines":{"/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/__init__.py":[1],"/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/encoder.py":[1,2,4,7,8,10,11,12,13,14,15,17,18,19,16],"/mnt/c/Users/thoma/Documents/dev/rocc/server/openapi_server/models/__init__.py":[4,6,7,8,9,10,11,12,13,14,15,16,17,18],
...
```

When running the same `pytest` command as part of tox, the format of the file `.coverage` is now binary and the command `coveralls` can not parse it when run in the terminal after `tox`. The coveralls command however works if it is included as part of the tox script.

**Comment by tschaffter** [comment]
PARTIAL SOLUTION: The package `coverage` - used by `pytest-cov` - generates the file `.coverage` in different format depending on the version of `coverage` installed.

- `coverage<5`: text format
- `coverage>=5`: SQLite format

It's important to note that the package `coveralls` and the command it provides only supports the text format, at least from what I've seen in posts online. Maybe `coverage>=5` has an option to generate `.coverage` in text format but I haven't found it.

IMPORTANT: Remember to delete the folder `.tox` each time the version of the dependencies change because tox is caching the dependencies in `.tox` and does not refresh them if `test-requirements.txt`, for example, changes.

**Comment by tschaffter** [comment]
I'm trying to put in place this example that fully use coveralls GH Action:
https://github.com/marketplace/actions/coveralls-github-action#complete-parallel-job-example

Here is the error I get:

```
Run coverallsapp/github-action@master
  with:
    github-token: ***
    flag-name: run-py38
    parallel: true
    path-to-lcov: ./coverage/lcov.info
    coveralls-endpoint: https://coveralls.io
  env:
    docker_repository: sagebionetworks/rocc
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
    PYTHON_ENV: py38
Using lcov file: ./coverage/lcov.info
Error: Lcov file not found.
```

The issue with the official coveralls GH Action are well summarized in [this ticket](https://github.com/coverallsapp/github-action/issues/30). Most importantly, this Action only works with LCOV files and it looks like the package `coverage` can not generate this format. The ticket suggests two approaches:

- Rely on a third-party GH Action, which I'm not inclined to adopt because of low community support/use
- Use the command `coveralls` as I initially attempted

I'll try the second route again

**Comment by tschaffter** [comment]
Actually it seems that the command coveralls supports `.coverage` files generated by `coverage>=5` when run in GH CI/CD workflow. The following versions are installed both on my local environment and during CI workflow: `coverage==5.3,coveralls==2.2.0`. Not sure where the difference lies, but at least the solution in #31 works successfully.
