### ISSUE TITLE
Add Challenge difficulty: "Good for Beginners" series 

### ISSUE THREAD

**Issue by jiaxinmachine88** [Sage-Bionetworks/rocc#34]
While the eventual goal is to standardize difficulty levels across Challenge schemas, we can start by curating a "good for beginner" series. 

Past challenges, like the [Beat AML Challenge](https://www.synapse.org/#!Synapse:syn20940518/wiki/596265) (Drug Response, Predict for binary values) have been appropriate for beginners/students. Are there challenges that: (1) predict for binary values and (2) do not require Dockers that may also be newcomer friendly?  

On the Challenge Details page, the UI implementation could look like a tag [(inspiration).](https://zindi.africa/competitions/road-segment-identification) 
On the Search page, the UI implementation could be a separate filter ([inspiration)](https://zindi.africa/competitions?difficulty%5B%5D=Good%20for%20beginners).

**Comment by tschaffter** [comment]
Dockerizing tools is now a best practices and hopefully is much easier for new participants than it was 5 years ago when I used it in my first big challenge. If we had demographic information about the participants of a challenge, this could give us a clue to identify beginner friendly challenges among past challenges. One approach could be to ask in the #challenge Slack channel if there are organizers who know about challenges that have been used for education or that they would consider easy.

In parallel, we could kick start a discussion around what defines an easy / intermediate / difficult challenges. This information would be displayed to organizers when they register their challenge.

**Comment by jiaxinmachine88** [comment]
Some relevant documentation: 

Here's the link to the Zindi Africa analysis: https://docs.google.com/document/d/1mdI4bY4nqfipD39t4vTCBKiEJrSz26gi3MQSNvgGofU/edit
Here's the link to the excel: https://docs.google.com/spreadsheets/d/1frG8tB4x_FbnR1-hMeLHb-4rC7y1Hsbx_7G6vNhZk6k/edit#gid=0
