### ISSUE TITLE
Highlight SME input on the data for Challenge details page

### ISSUE THREAD

**Issue by jiaxinmachine88** [Sage-Bionetworks/rocc#35]
We want to enable Organizers to highlight whether their Challenge dataset was annotated/curated with clinical subject matter expertise. 

Consider ways of more visibly highlighting the clinical institutions (e.g: Penn Medicine, UW Medicine, Radiological Society, etc) contributions towards the dataset, on the Challenge details page.

**Comment by tschaffter** [comment]
Challenge sponsors are now shown on the challenge details page.
